// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3pnE2iT0g4So7_6dpzaJ38cxniNOrMIM',
    appId: '1:60378391671:web:ff15c8da5476d4a22bd272',
    messagingSenderId: '60378391671',
    projectId: 'login-project-7a603',
    authDomain: 'login-project-7a603.firebaseapp.com',
    storageBucket: 'login-project-7a603.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDj9sLU_NRmEFY-IgH8cYl3HMRqei8Oe1o',
    appId: '1:60378391671:android:ace5cf6485cfecf02bd272',
    messagingSenderId: '60378391671',
    projectId: 'login-project-7a603',
    storageBucket: 'login-project-7a603.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKN1yCKpKZpoD-EjEv6tCZB6UWxq4gPeM',
    appId: '1:60378391671:ios:c1e2add719e76efa2bd272',
    messagingSenderId: '60378391671',
    projectId: 'login-project-7a603',
    storageBucket: 'login-project-7a603.appspot.com',
    iosBundleId: 'com.example.loginassegmnt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKN1yCKpKZpoD-EjEv6tCZB6UWxq4gPeM',
    appId: '1:60378391671:ios:fa68ee887cce766b2bd272',
    messagingSenderId: '60378391671',
    projectId: 'login-project-7a603',
    storageBucket: 'login-project-7a603.appspot.com',
    iosBundleId: 'com.example.loginassegmnt.RunnerTests',
  );
}
